source "https://rubygems.org"

group :test do
  gem 'selenium-webdriver'
  gem 'cucumber', '~> 5.1.1'
  gem 'rspec', '~> 3.9.0'
  gem 'webdrivers', '~> 4.0', require: false
end
group :test do
  gem 'cucumber-rails', require: false
  # database_cleaner is not mandatory, but highly recommended
  gem 'database_cleaner'
end